# Diccionario con información de los trabajadores
trabajadores = {
    "Juan": {"horas_trabajadas": 45, "tardanzas": 2},
    "Maria": {"horas_trabajadas": 38, "tardanzas": 4},
    "Pedro": {"horas_trabajadas": 50, "tardanzas": 1},
    "Ana": {"horas_trabajadas": 42, "tardanzas": 3},
    "Luis": {"horas_trabajadas": 40, "tardanzas": 0}
}

letters = [(x, chr(x)) for x, idx in enumerate(range(5), start=65)]
d1 = dict(letters)
print (letters)

perros = ['firulais', 'lola', 'pluto', 'nico']

contador = 1
#for nombre in perros:
    #print(contador, nombre)
    #contador+=1

#for conta, nom in enumerate(perros,start=1):
    #print(conta,nom)